import Head from 'next/head'
import styles from '../styles/Akemi.module.css'

export default function Akemi(){
    return(
        <div>
            <Head>
                <title>Akemi</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/heart.ico" />
            </Head>

            <div className={styles.container}>
                <div className={styles.box}>
                    <h2>Oi mor</h2>
                    <span>
                        Eu te amo!
                            Não tenho dinheiro para te dar um presente de 2 anos :( Não sou bonito para tirar uma foto pra comemorar os 2 anos :( Tudo o que eu tenho já te ofereci, que foi amor e carinho, Talvez não seja muito, ou muitas das vezes pra mim não parece que estou fazendo o bastante, mas eu tento, e não vou deixar de tentar. Sou meio cavalo as vezes, acontece de soltar uma ou outra mas infelizmente eu sou assim, sempre tentando mudar e ser melhor, então tenha paciencia comigo, tenha paciencia com a gente. 2 anos ja foram, e a gente continua na mesma, eu quero que esse ano seja diferente, ja temos a loja de cubo, ou pelo menos o que vai virar ela, eu quero fazer mais coisas com você, saber tudo sobre você, discutir sobre assuntos que nunca discutimos, e brigar menos, porque ficar sem brigar eu sei que não da.
                            É isso, Feliz 2 anos.
                    </span>
                </div>
            </div>
        </div>
    )
}


 